services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge